# **Day_24**

# **Pandas import**

In [3]:
import pandas as pd

In [6]:
df = pd.read_csv('/content/DataSheet.csv')
print(df)

    OrderID  CustomerID CustomerName        City  ProductID ProductName  \
0         1         101        Rahim       Dhaka        201      Laptop
1         2         102        Karim      Khulna        202       Mouse
2         3         103        Jamil       Dhaka        203    Keyboard
3         4         104        Salma  Chattogram        204     Printer
4         5         105        Nadia    Rajshahi        205     Monitor
5         6         106       Shohan      Shylet        206      Router
6         7         107        Tania       Dhaka        207         SSD
7         8         108        Rifat      Khulna        208         HDD
8         9         109        Imran     Barisal        209         UPS
9        10         110         Nila     Rangpur        210     Scanner
10       11         101        Rahim       Dhaka        201      Laptop
11       12         102        Karim      Khulna        202       Mouse
12       13         103        Jamil       Dhaka        203    Keyboard
13       14         104        Salma  Chattogram        204     Printer
14       15         105        Nadia    Rajshahi        205     Monitor
15       16         106       Shohan      Shylet        206      Router
16       17         107        Tania       Dhaka        207         SSD
17       18         108        Rifat      Khulna        208         HDD
18       19         109        Imran     Barisal        209         UPS
19       20         110         Nila     Rangpur        210     Scanner
20       21         101        Rahim       Dhaka        201      Laptop
21       22         102        Karim      Khulna        202       Mouse
22       23         103        Jamil       Dhaka        203    Keyboard
23       24         104        Salma  Chattogram        204     Printer
24       25         105        Nadia    Rajshahi        205     Monitor
25       26         106       Shohan      Shylet        206      Router
26       27         107        Tania       Dhaka        207         SSD
27       28         108        Rifat      Khulna        208         HDD
28       29         109        Imran     Barisal        209         UPS
29       30         110         Nila     Rangpur        210     Scanner
30       31         101        Rahim       Dhaka        201      Laptop
31       32         102        Karim      Khulna        202       Mouse
32       33         103        Jamil       Dhaka        203    Keyboard
33       34         104        Salma  Chattogram        204     Printer
34       35         105        Nadia    Rajshahi        205     Monitor
35       36         106       Shohan      Shylet        206      Router
36       37         107        Tania       Dhaka        207         SSD
37       38         108        Rifat      Khulna        208         HDD
38       39         109        Imran     Barisal        209         UPS
39       40         110         Nila     Rangpur        210     Scanner
40       41         101        Rahim       Dhaka        201      Laptop
41       42         102        Karim      Khulna        202       Mouse
42       43         103        Jamil       Dhaka        203    Keyboard
43       44         104        Salma  Chattogram        204     Printer
44       45         105        Nadia    Rajshahi        205     Monitor
45       46         106       Shohan      Shylet        206      Router
46       47         107        Tania       Dhaka        207         SSD
47       48         108        Rifat      Khulna        208         HDD
48       49         109        Imran     Barisal        209         UPS
49       50         110         Nila     Rangpur        210     Scanner
50       51         101        Rahim       Dhaka        201      Laptop
51       52         102        Karim      Khulna        202       Mouse
52       53         103        Jamil       Dhaka        203    Keyboard
53       54         104        Salma  Chattogram        204     Printer
54       55         105        Nadia    Rajshahi        205     Monitor
55       56         106       Shohan      Shylet        206      Router
56       57         107        Tania       Dhaka        207         SSD
57       58         108        Rifat      Khulna        208         HDD
58       59         109        Imran     Barisal        209         UPS
59       60         110         Nila     Rangpur        210     Scanner

       Category  OrderDate  Quantity  UnitPrice   Amout
0   Electonicks   3/1/2025         3      50000  150000
1   Electonicks   5/1/2025         3       1000    3000
2   Electonicks   7/1/2025         2       1500    3000
3   Electonicks   9/1/2025         3      15000   45000
4   Electonicks  11/1/2025         3      12000   36000
5       Network  13/1/2025         4       3000   12000
6       Storage  15/1/2025         4       6000   24000
7       Storage  17/1/2025         5       5000   25000
8         Power  19/1/2025         4       8000   32000
9   Electonicks  21/1/2025         3      10000   30000
10  Electonicks  23/1/2025         4      50000  200000
11  Electonicks  25/1/2025         2       1000    2000
12  Electonicks  27/1/2025         2       1500    3000
13  Electonicks  29/1/2025         4      15000   60000
14  Electonicks  31/1/2025         5      12000   60000
15      Network   2/2/2025         3       3000    9000
16      Storage   4/2/2025         1       6000    6000
17      Storage   6/2/2025         3       5000   15000
18        Power   8/2/2025         1       8000    8000
19  Electonicks  10/2/2025         5      10000   50000
20  Electonicks  12/2/2025         2      50000  100000
21  Electonicks  14/2/2025         2       1000    2000
22  Electonicks  16/2/2025         4       1500    6000
23  Electonicks  18/2/2025         4      15000   60000
24  Electonicks  20/2/2025         4      12000   48000
25      Network  22/2/2025         1       3000    3000
26      Storage  24/2/2025         2       6000   12000
27      Storage  26/2/2025         5       5000    2500
28        Power  28/2/2025         4       8000   32000
29  Electonicks   2/3/2025         2      10000   20000
30  Electonicks   4/3/2025         3      50000  150000
31  Electonicks   6/3/2025         5       1000    5000
32  Electonicks   8/3/2025         5       1500    7500
33  Electonicks  10/3/2025         1      15000   15000
34  Electonicks  12/3/2025         1      12000   12000
35      Network  14/3/2025         1       3000    3000
36      Storage  16/3/2025         3       6000   18000
37      Storage  18/3/2025         1       5000    5000
38        Power  20/3/2025         5       8000   40000
39  Electonicks  22/3/2025         5      10000   50000
40  Electonicks  24/3/2025         1      50000   50000
41  Electonicks  26/3/2025         3       1000    3000
42  Electonicks  28/3/2025         1       1500    1500
43  Electonicks  30/3/2025         5      15000   75000
44  Electonicks   1/4/2025         5      12000   60000
45      Network   3/4/2025         4       3000   12000
46      Storage   5/4/2025         3       6000   18000
47      Storage   7/4/2025         3       5000   15000
48        Power   9/4/2025         3       8000   24000
49  Electonicks  11/4/2025         5      10000   50000
50  Electonicks  13/4/2025         5      50000  250000
51  Electonicks  15/4/2025         1       1000    1000
52  Electonicks  17/4/2025         4       1500    6000
53  Electonicks  19/4/2025         4      15000   60000
54  Electonicks  21/4/2025         2      12000   24000
55      Network  23/4/2025         4       3000   12000
56      Storage  25/4/2025         1       6000    6000
57      Storage  27/4/2025         5       5000   25000
58        Power  29/4/2025         5       8000   40000
59  Electonicks   1/5/2025         4      10000   40000

In [7]:
df.head()

,OrderID,CustomerID,CustomerName,City,ProductID,ProductName,Category,OrderDate,Quantity,UnitPrice,Amout
0,1,101,Rahim,Dhaka,201,Laptop,Electonicks,3/1/2025,3,50000,150000
1,2,102,Karim,Khulna,202,Mouse,Electonicks,5/1/2025,3,1000,3000
2,3,103,Jamil,Dhaka,203,Keyboard,Electonicks,7/1/2025,2,1500,3000
3,4,104,Salma,Chattogram,204,Printer,Electonicks,9/1/2025,3,15000,45000
4,5,105,Nadia,Rajshahi,205,Monitor,Electonicks,11/1/2025,3,12000,36000

In [ ]:
df.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'City', 'ProductID',
       'ProductName', 'Category', 'OrderDate', 'Quantity', 'UnitPrice',
       'Amout'],
      dtype='object')

In [ ]:
df['Amout'].head()

0    150000
1      3000
2      3000
3     45000
4     36000
Name: Amout, dtype: int64

In [11]:
df[['Amout','ProductName']].head()

    Amout ProductName
0  150000      Laptop
1    3000       Mouse
2    3000    Keyboard
3   45000     Printer
4   36000     Monitor

In [16]:
df[df['Amout']>35000].head()

,OrderID,CustomerID,CustomerName,City,ProductID,ProductName,Category,OrderDate,Quantity,UnitPrice,Amout
0,1,101,Rahim,Dhaka,201,Laptop,Electonicks,3/1/2025,3,50000,150000
3,4,104,Salma,Chattogram,204,Printer,Electonicks,9/1/2025,3,15000,45000
4,5,105,Nadia,Rajshahi,205,Monitor,Electonicks,11/1/2025,3,12000,36000
10,11,101,Rahim,Dhaka,201,Laptop,Electonicks,23/1/2025,4,50000,200000
13,14,104,Salma,Chattogram,204,Printer,Electonicks,29/1/2025,4,15000,60000

In [17]:
df[df['Amout']>35000][['ProductName','Amout']].head()

   ProductName   Amout
0       Laptop  150000
3      Printer   45000
4      Monitor   36000
10      Laptop  200000
13     Printer   60000

In [18]:
df[df['Amout']>35000][['ProductName','Amout','City']].head()

   ProductName   Amout        City
0       Laptop  150000       Dhaka
3      Printer   45000  Chattogram
4      Monitor   36000    Rajshahi
10      Laptop  200000       Dhaka
13     Printer   60000  Chattogram

In [22]:
df[(df['Amout']>15000) & (df['City'] == 'Dhaka')][['ProductName','Amout','City']].head()

   ProductName   Amout   City
0       Laptop  150000  Dhaka
6          SSD   24000  Dhaka
10      Laptop  200000  Dhaka
20      Laptop  100000  Dhaka
30      Laptop  150000  Dhaka

In [23]:
df[(df['Amout']>15000) & (df['City'] == 'Dhaka')][['ProductName','Amout','City']].count()

ProductName    9
Amout          9
City           9
dtype: int64

In [26]:
df[(df['Amout']>15000) & (df['City'] == 'Dhaka') & (df['ProductName'] == 'Laptop')][['ProductName','Amout','City']].head()

   ProductName   Amout   City
0       Laptop  150000  Dhaka
10      Laptop  200000  Dhaka
20      Laptop  100000  Dhaka
30      Laptop  150000  Dhaka
40      Laptop   50000  Dhaka