In [1]:
import pandas as pd

In [2]:
age = [10, 20, 30, 40, 50]

In [3]:
data = pd.DataFrame(age);
print(data)

    0
0  10
1  20
2  30
3  40
4  50

# **Data Frame**

In [8]:
data1 = {
    'Product': ['Laptop', 'Mobile', 'Mouse'],
    'Price': [1000, 2000, 300]
}
print(data1)
print('=================================================')
pd.DataFrame(data1)

{'Product': ['Laptop', 'Mobile', 'Mouse'], 'Price': [1000, 2000, 300]}
=================================================

  Product  Price
0  Laptop   1000
1  Mobile   2000
2   Mouse    300

# **Data Frame**

In [11]:
df = pd.read_csv('/DataSheet.csv')

# **Show total data**

In [12]:
df

,OrderID,CustomerID,CustomerName,City,ProductID,ProductName,Category,OrderDate,Quantity,UnitPrice,Amout
0,1,101,Rahim,Dhaka,201,Laptop,Electonicks,3/1/2025,3,50000,150000
1,2,102,Karim,Khulna,202,Mouse,Electonicks,5/1/2025,3,1000,3000
2,3,103,Jamil,Dhaka,203,Keyboard,Electonicks,7/1/2025,2,1500,3000
3,4,104,Salma,Chattogram,204,Printer,Electonicks,9/1/2025,3,15000,45000
4,5,105,Nadia,Rajshahi,205,Monitor,Electonicks,11/1/2025,3,12000,36000
5,6,106,Shohan,Shylet,206,Router,Network,13/1/2025,4,3000,12000
6,7,107,Tania,Dhaka,207,SSD,Storage,15/1/2025,4,6000,24000
7,8,108,Rifat,Khulna,208,HDD,Storage,17/1/2025,5,5000,25000
8,9,109,Imran,Barisal,209,UPS,Power,19/1/2025,4,8000,32000
9,10,110,Nila,Rangpur,210,Scanner,Electonicks,21/1/2025,3,10000,30000
10,11,101,Rahim,Dhaka,201,Laptop,Electonicks,23/1/2025,4,50000,200000
11,12,102,Karim,Khulna,202,Mouse,Electonicks,25/1/2025,2,1000,2000
12,13,103,Jamil,Dhaka,203,Keyboard,Electonicks,27/1/2025,2,1500,3000
13,14,104,Salma,Chattogram,204,Printer,Electonicks,29/1/2025,4,15000,60000
14,15,105,Nadia,Rajshahi,205,Monitor,Electonicks,31/1/2025,5,12000,60000
15,16,106,Shohan,Shylet,206,Router,Network,2/2/2025,3,3000,9000
16,17,107,Tania,Dhaka,207,SSD,Storage,4/2/2025,1,6000,6000
17,18,108,Rifat,Khulna,208,HDD,Storage,6/2/2025,3,5000,15000
18,19,109,Imran,Barisal,209,UPS,Power,8/2/2025,1,8000,8000
19,20,110,Nila,Rangpur,210,Scanner,Electonicks,10/2/2025,5,10000,50000
20,21,101,Rahim,Dhaka,201,Laptop,Electonicks,12/2/2025,2,50000,100000
21,22,102,Karim,Khulna,202,Mouse,Electonicks,14/2/2025,2,1000,2000
22,23,103,Jamil,Dhaka,203,Keyboard,Electonicks,16/2/2025,4,1500,6000
23,24,104,Salma,Chattogram,204,Printer,Electonicks,18/2/2025,4,15000,60000
24,25,105,Nadia,Rajshahi,205,Monitor,Electonicks,20/2/2025,4,12000,48000
25,26,106,Shohan,Shylet,206,Router,Network,22/2/2025,1,3000,3000
26,27,107,Tania,Dhaka,207,SSD,Storage,24/2/2025,2,6000,12000
27,28,108,Rifat,Khulna,208,HDD,Storage,26/2/2025,5,5000,2500
28,29,109,Imran,Barisal,209,UPS,Power,28/2/2025,4,8000,32000
29,30,110,Nila,Rangpur,210,Scanner,Electonicks,2/3/2025,2,10000,20000
30,31,101,Rahim,Dhaka,201,Laptop,Electonicks,4/3/2025,3,50000,150000
31,32,102,Karim,Khulna,202,Mouse,Electonicks,6/3/2025,5,1000,5000
32,33,103,Jamil,Dhaka,203,Keyboard,Electonicks,8/3/2025,5,1500,7500
33,34,104,Salma,Chattogram,204,Printer,Electonicks,10/3/2025,1,15000,15000
34,35,105,Nadia,Rajshahi,205,Monitor,Electonicks,12/3/2025,1,12000,12000
35,36,106,Shohan,Shylet,206,Router,Network,14/3/2025,1,3000,3000
36,37,107,Tania,Dhaka,207,SSD,Storage,16/3/2025,3,6000,18000
37,38,108,Rifat,Khulna,208,HDD,Storage,18/3/2025,1,5000,5000
38,39,109,Imran,Barisal,209,UPS,Power,20/3/2025,5,8000,40000
39,40,110,Nila,Rangpur,210,Scanner,Electonicks,22/3/2025,5,10000,50000
40,41,101,Rahim,Dhaka,201,Laptop,Electonicks,24/3/2025,1,50000,50000
41,42,102,Karim,Khulna,202,Mouse,Electonicks,26/3/2025,3,1000,3000
42,43,103,Jamil,Dhaka,203,Keyboard,Electonicks,28/3/2025,1,1500,1500
43,44,104,Salma,Chattogram,204,Printer,Electonicks,30/3/2025,5,15000,75000
44,45,105,Nadia,Rajshahi,205,Monitor,Electonicks,1/4/2025,5,12000,60000
45,46,106,Shohan,Shylet,206,Router,Network,3/4/2025,4,3000,12000
46,47,107,Tania,Dhaka,207,SSD,Storage,5/4/2025,3,6000,18000
47,48,108,Rifat,Khulna,208,HDD,Storage,7/4/2025,3,5000,15000
48,49,109,Imran,Barisal,209,UPS,Power,9/4/2025,3,8000,24000
49,50,110,Nila,Rangpur,210,Scanner,Electonicks,11/4/2025,5,10000,50000
50,51,101,Rahim,Dhaka,201,Laptop,Electonicks,13/4/2025,5,50000,250000
51,52,102,Karim,Khulna,202,Mouse,Electonicks,15/4/2025,1,1000,1000
52,53,103,Jamil,Dhaka,203,Keyboard,Electonicks,17/4/2025,4,1500,6000
53,54,104,Salma,Chattogram,204,Printer,Electonicks,19/4/2025,4,15000,60000
54,55,105,Nadia,Rajshahi,205,Monitor,Electonicks,21/4/2025,2,12000,24000
55,56,106,Shohan,Shylet,206,Router,Network,23/4/2025,4,3000,12000
56,57,107,Tania,Dhaka,207,SSD,Storage,25/4/2025,1,6000,6000
57,58,108,Rifat,Khulna,208,HDD,Storage,27/4/2025,5,5000,25000
58,59,109,Imran,Barisal,209,UPS,Power,29/4/2025,5,8000,40000
59,60,110,Nila,Rangpur,210,Scanner,Electonicks,1/5/2025,4,10000,40000

# **First 5 data**

In [13]:
df.head()

,OrderID,CustomerID,CustomerName,City,ProductID,ProductName,Category,OrderDate,Quantity,UnitPrice,Amout
0,1,101,Rahim,Dhaka,201,Laptop,Electonicks,3/1/2025,3,50000,150000
1,2,102,Karim,Khulna,202,Mouse,Electonicks,5/1/2025,3,1000,3000
2,3,103,Jamil,Dhaka,203,Keyboard,Electonicks,7/1/2025,2,1500,3000
3,4,104,Salma,Chattogram,204,Printer,Electonicks,9/1/2025,3,15000,45000
4,5,105,Nadia,Rajshahi,205,Monitor,Electonicks,11/1/2025,3,12000,36000

# **Last 5 data**

In [14]:
df.tail()

,OrderID,CustomerID,CustomerName,City,ProductID,ProductName,Category,OrderDate,Quantity,UnitPrice,Amout
55,56,106,Shohan,Shylet,206,Router,Network,23/4/2025,4,3000,12000
56,57,107,Tania,Dhaka,207,SSD,Storage,25/4/2025,1,6000,6000
57,58,108,Rifat,Khulna,208,HDD,Storage,27/4/2025,5,5000,25000
58,59,109,Imran,Barisal,209,UPS,Power,29/4/2025,5,8000,40000
59,60,110,Nila,Rangpur,210,Scanner,Electonicks,1/5/2025,4,10000,40000

# **Find out total row and coloum**

In [15]:
df.shape

(60, 11)

# **Data set descriotion**

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   OrderID       60 non-null     int64
 1   CustomerID    60 non-null     int64
 2   CustomerName  60 non-null     object
 3   City          60 non-null     object
 4   ProductID     60 non-null     int64
 5   ProductName   60 non-null     object
 6   Category      60 non-null     object
 7   OrderDate     60 non-null     object
 8   Quantity      60 non-null     int64
 9   UnitPrice     60 non-null     int64
 10  Amout         60 non-null     int64
dtypes: int64(6), object(5)
memory usage: 5.3+ KB

# **Data set statistics**

In [17]:
df.describe()

,OrderID,CustomerID,ProductID,Quantity,UnitPrice,Amout
count,60.000000,60.00000,60.00000,60.000000,60.000000,60.000000
mean,30.500000,105.50000,205.50000,3.200000,11150.000000,35608.333333
std,17.464249,2.89652,2.89652,1.423769,13764.453113,47711.801801
min,1.000000,101.00000,201.00000,1.000000,1000.000000,1000.000000
25%,15.750000,103.00000,203.00000,2.000000,3000.000000,6000.000000
50%,30.500000,105.50000,205.50000,3.000000,7000.000000,19000.000000
75%,45.250000,108.00000,208.00000,4.000000,12000.000000,48500.000000
max,60.000000,110.00000,210.00000,5.000000,50000.000000,250000.000000

# **Check the null value if have!**

In [18]:
df.isnull().sum()

OrderID         0
CustomerID      0
CustomerName    0
City            0
ProductID       0
ProductName     0
Category        0
OrderDate       0
Quantity        0
UnitPrice       0
Amout           0
dtype: int64

# **See all the column**

In [20]:
df.columns

Index(['OrderID', 'CustomerID', 'CustomerName', 'City', 'ProductID',
       'ProductName', 'Category', 'OrderDate', 'Quantity', 'UnitPrice',
       'Amout'],
      dtype='object')

# **Average ravenue/Mean**

In [23]:
df['Amout'].mean()

np.float64(35608.333333333336)